### ISSUE TITLE
evaluate moving to parcel v2

### ISSUE THREAD

**Issue by purplecabbage** [adobe/aio-lib-web#147]
parcel-bundler v1.x is now deprecated, and showing this message:
```
DEPRECATED ⚠️  - Parcel v1 is no longer maintained. Please migrate to v2, which is published
under the 'parcel' package. See https://v2.parceljs.org/getting-started/migration for details.
```

We need to verify that everything still functions as expected, since this is a major bump.
Also, of note, parcel still lists 'latest' as a beta version => 2.0.0-beta.2

**Comment by meryllblanchet** [comment]
Good point. @Himavanth is evaluating our move to NodeJS 14 support for CLI & Plugins (incl. underlying libraries) and it seems like we'd have to move to parcel v2 as v1 has dependencies which are not compatible with NodeJS 14.
